title: 3D Design and Virtual Reality
description: Macalester College Spring Professional Activities Workshop 2016
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
